apiVersion: v1
kind: Secret
metadata:
  name: bentro-app-secret
  namespace: bentro
type: Opaque
data:
  # Base64 encoded "postgres"
  DB_PASSWORD: cG9zdGdyZXM=
  # Base64 encoded "super-secret-jwt-key-change-in-prod"
  JWT_SECRET: c3VwZXItc2VjcmV0LWp3dC1rZXktY2hhbmdlLWluLXByb2Q=
