{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  ports:
    - port: {{ .Values.postgresql.service.port }}
  selector:
    app: {{ .Release.Name }}-postgres
{{- end }}
