apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  # In a real scenario, we would allow these to be passed in via values and base64 encoded here
  # For the "Happy Path" demo, we'll hardcode the defaults base64'd or use a helper function.
  # "postgres" -> cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
  # "super-secret-jwt-key-change-in-prod" -> c3VwZXItc2VjcmV0LWp3dC1rZXktY2hhbmdlLWluLXByb2Q=
  JWT_SECRET: c3VwZXItc2VjcmV0LWp3dC1rZXktY2hhbmdlLWluLXByb2Q=
